### ISSUE TITLE
A couple function keys

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#100]
There's a couple function keys from the original game that may be easily addable right now:
F1 - Open character sheet
F8 - Toggle compass

Toggling compass should be a XOR of 0x2000 or 0x0020, possibly on the GameOptions WORD in the SAVEENGN file, as described in the Wiki. For a new character I created the changing value was at offset 0x425 in the SAVEENGN file.

**Comment by afritz1** [comment]
See commit c054048493c4c9dde48f304001fc2fb247bd52d9.

I haven't touched any of the save data yet since I'm still focusing on other things (getting the level data right), but I plan on adding it at some point (probably an ArenaSaveData class or something in the assets folder).

**Comment by Allofich** [comment]
Since the main point of this was fixed, I'll move the comment about the save file to the save data issue.
