### ISSUE TITLE
Level transition sound

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#106]
When the player transitions between interior levels, there's a sound that plays. It's almost like `NHIT.VOC`, but I don't think it's that, and I haven't found anything closer. Any ideas?

**Comment by Carmina16** [comment]
Are you sure there is a sound? It looks like random static to me.

**Comment by afritz1** [comment]
It seems to play pretty consistently. I've checked through every .VOC file in the game's data and none of them match up closely enough, so it is a possibility that it's some unintended sound effect. But again, the fact that it's so consistent tells me that it's intentional.

**Comment by Allofich** [comment]
I just tested it, and I think it may just be a glitch related to cutting off the footstep sound. It doesn't seem to play unless the footstep sound is playing when you transition the level, and I noticed that an in-progress footstep sound is no longer playing once the transition finishes.

**Comment by Allofich** [comment]
Actually I think the footstep sound maybe isn't being "cut off", the tail end of it is just obscured by the other sound. I tested a bunch of times in a row now and once I was able to get through during footstep playback and it played normally through the transition. Also I tried swinging my weapon while transitioning but nothing seems to happen, the swing sounds just plays normally, although it's a little hard to get the timing right.

**Comment by Allofich** [comment]
Just to be sure we're talking about the same thing, here is the sound I hear.

[Sound.zip](https://github.com/afritz1/OpenTESArena/files/1659550/Sound.zip)

**Comment by afritz1** [comment]
A bug with the footsteps is much more plausible. And yeah, that's the sound I was referring to: on the tail end of the footstep. Just a guess (from my limited knowledge of audio), but Arena probably has a separate array for each set of 8-bit PCM samples, and only some of them get cleared when moving between levels, like the footstep sound for example.

Another guess, that since some sounds like footsteps (`DIRTL.VOC`, `DIRTR.VOC`) only seem to appear in interior .INF files, they are the only ones that get cleared when moving between levels, while others (`ARROWFR.VOC`, `BASH.VOC`, ...) are untouched (presumably).

This seems to be a bug in the original as a result of not properly sharing/clearing data between levels, so I don't think we want to replicate this behavior. I guess there shouldn't be a level transition sound after all.
