### ISSUE TITLE
No music on macOS

### ISSUE THREAD

**Issue by Thunderforge** [afritz1/OpenTESArena#107]
Sound isn't working in the 0.6.0 release of OpenTESArena. It should be fairly easy to get WildMidi set up with that.

**Comment by afritz1** [comment]
Commit 43550ab1a4359025bce1f3fa2693343ea9c50f70 might be relevant. The `MidiConfig` string wasn't getting the base path prepended, so it likely wasn't looking inside the macOS .app correctly before.

**Comment by afritz1** [comment]
I think this can be closed.
