### ISSUE TITLE
Area name in automap, on travel map

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#110]
Great to see the recent progress in loading cities. I did some testing and have found out some information about the area name seen in the automap. Sorry if this is all known information.

START.MIF - This is hard-coded. In the same function that loads the "START.MIF" string, the nearby "Imperial Dungeons" string is also loaded.

IMPPAL.MIF - This retains the name "Imperial City" from the city you're in when you click to enter it. There is no "Imperial City" string in the executable so I think it just leaves the name as what it was when the player accessed the gate to enter IMPPAL.MIF.

Note that there is a separate string in the executable "the Imperial City", which is used in the dialogue when you arrive ("You have arrived in the Imperial City.")

Random dungeon - The name in the automap is left blank.

Story dungeon - The name is gotten from the CITYDATA file being used for that save slot. I don't know exactly what the relationship between the save slot CITYDATA files and CITYDATA.64 and CITYDATA.65 is, but  CITYDATA.65 seems to remain unchanged as the initial values, while CITYDATA.64 can change and is probably used as live data somehow.

Each name entry is 25 bytes long. It seems that after all the towns, etc., the two story dungeons appear, first the "second one" with the staff piece, and then the "first one" with the tablet, etc. The name is used both on the automap and on the travel map.

Also, a potentially useful trick if you want to access any of the story dungeons in the original game: Change the final, 25th byte of a dungeon entry from 00 to 02 to reveal it on the travel map.

**Comment by afritz1** [comment]
Thanks. I think this will be useful when implementing traveling code, so it can update with the proper location name. Most location names are in CITYDATA.00, but there are a couple exceptions like the Imperial Dungeons.

**Comment by Allofich** [comment]
Sorry, just in case it wasn't clear, "Imperial Dungeons" is a string in the .exe. It's hardcoded to be the name of the dungeon you start in on a new game, just as "start.mif" is a string in the .exe and hardcoded to be the .mif filename.

CITYDATA.00 might just be the data initialized from if you load the first save slot, not sure. I think the loaded data is then copied over to CITYDATA.64, which maybe is what the game uses for live changes, but I haven't confirmed that. CITYDATA.65 might be used as the default values to initialize from on a new game, but I haven't confirmed that, either, so these are guesses.

**Comment by afritz1** [comment]
>Sorry, just in case it wasn't clear, "Imperial Dungeons" is a string in the .exe.

Oh. What I said and what I meant were two different things 😄.

I believe the default city data is in `CITYDATA.00`, since that's what I'm loading all the world map provinces and locations from. I'll look into the other city data files once I investigate save files.

**Comment by Allofich** [comment]
> Oh. What I said and what I meant were two different things.
Well I may have misunderstood you. It just kind of sounded like maybe you were expecting the name to be in the CITYDATA file and wondering where it was since it wasn't in there, and when I read back over my message it wasn't quite as clear as I had intended. But no harm done :)

**Comment by afritz1** [comment]
I think the automap names are all correct now. I haven't gotten arrival text implemented yet, so I still need to take care of the line you mentioned about "You have arrived in the Imperial City".

**Comment by Allofich** [comment]
Looks like everything I mentioned is working now. If you want to be 100% about it you could also load the "START.MIF" and "IMPPAL.MIF" strings from the Arena executable, but functionally everything is in. I think you can close this one whenever you want to!
