### ISSUE TITLE
Messages persist between dungeon loads

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#117]
Testing out the latest progress, I noticed that messages triggered by entering a voxel (for example the message you get right as entering Stonekeep) will continue to show on the screen if you travel to another area before the message has finished showing. I testing in the original game and they do not persist there.

**Comment by Allofich** [comment]
I just tested and actually the red messages (tested the "position" one and "it'd be a miracle if you picked this lock") will continue to show even if you fast travel.

Their display "countdown" does not decrease if you pause the game by opening a screen like the automap, which seems to be the same in OpenTESArena.

Are there yellow timed messages?

**Comment by afritz1** [comment]
The yellow messages are for things like "You are diseased/drunk/silenced".

**Comment by Allofich** [comment]
Ah Ok. Let me try the drunk one. I'm guessing based on the red messages that it probably will still show. It's probably just the orange ones that are tied to dungeons that are not shown.

Not that you have to replicate original behavior THIS closely, of course. But, if it's not an inconvenience, might as well.

**Comment by afritz1** [comment]
It'd be really easy to make the messages not show. Something as simple as:
```C++
auto &gameData = game.getGameData();
gameData.getTriggerText().reset();
```
in `FastTravelSubPanel::switchToNextPanel()`.

**Comment by Allofich** [comment]
Good to hear. By the way let me just take the moment to say that I love how methodically you're proceeding with this project, even pulling the original data directly from the executable, and trying to recreate original behavior and everything. Anyway, I'll go test the drunk message now.

**Comment by afritz1** [comment]
:+1:

**Comment by Allofich** [comment]
What was I thinking, the drunk message is a no-go because it ends way before you can leave the tavern and initiate fast travel. So I'd have to find a monster that did one of those status effects and then try to initiate a fast travel, but I'm not really prepared to go to those lengths right now, haha. This would probably be comparatively easy to confirm through reverse-engineering anyway, so maybe @Carmina16 can comment.

**Comment by afritz1** [comment]
I just tested getting diseased by rats in Stonekeep, then fast traveled to the nearest town, and the "You are diseased" text does indeed persist, so it looks like only the orange "lore" text is hidden.

**Comment by Allofich** [comment]
Great, well we've got it all covered then!

**Comment by Carmina16** [comment]
A couple of observations:

**Comment by afritz1** [comment]
Good to know. I've been using a variable duration based on the text length, which works a lot better for longer messages (because if they're all just 40 frames then some of the longer ones aren't readable at a comfortable pace). I don't think I'm covering the second bullet yet, but the variable duration works well enough that adding the permanent display is a low priority.
