### ISSUE TITLE
Crash when as soon as i luanch the game

### ISSUE THREAD

**Issue by Aaron-Paul-Hancock-Jr** [afritz1/OpenTESArena#118]
I just launched OpenTESArena, but the game just terminate right away when i launch

**Comment by afritz1** [comment]
Are you on Windows? Are there any error messages? What is your `ArenaPath`? It needs to point to the `ARENA` folder, wherever it is that you installed it.

**Comment by afritz1** [comment]
@Aaron-Paul-Hancock-Jr can you try the 0.7.0 release and tell me if it works on your computer?

**Comment by Allofich** [comment]
I think it's safe to assume this was just a configuration error. Seems OK to close to me.

**Comment by afritz1** [comment]
Maybe they figured it out on their own. If not, then I can reopen it.
