### ISSUE TITLE
Game crashes on exit in MSYS2 build.

### ISSUE THREAD

**Issue by enderdrag64** [afritz1/OpenTESArena#123]
I tried building the latest master code in MSYS2 using the build guide, with the only difference being I used my own build of WildMidi 0.4.3. In my build the game will crash on exit. It doesn't seem to be caused by WildMidi, as removing eawpats from the data folder doesn't fix it unlike issue #69 .

**Comment by enderdrag64** [comment]
The debug console throws the error "[Utilities/Platform.cpp(195)] Error: Not implemented."

**Comment by enderdrag64** [comment]
Update: Manually defining _WINDOWS in platform.cpp fixes the crash.

**Comment by afritz1** [comment]
Hmm, looks like `_WINDOWS` isn't defined in MSYS2. Maybe it should be `_WIN32` or `__MINGW32__` instead. Could you try replacing `#if defined(_WINDOWS)` with one of these and then tell me if it works?
```C++
#if defined(_WIN32)
```
```C++
#if defined(_WIN32) || defined(__MINGW32__)
```

**Comment by enderdrag64** [comment]
I tried them both and they exit without crashing.

**Comment by afritz1** [comment]
Okay, I'll change `_WINDOWS` to `_WIN32` then. Thanks for reporting this issue.
