### ISSUE TITLE
0.9.0 release and video

### ISSUE THREAD

**Issue by neuromancer** [afritz1/OpenTESArena#144]
Don't forget to add 0.9.0 in [the release section](https://github.com/afritz1/OpenTESArena/releases) as well as add [a video](https://www.youtube.com/channel/UCJpmkgtHRIxR7aOpi909GKw) showing the new features of that release :smile:

**Comment by afritz1** [comment]
The Windows builds are ready, just need to make the video and get the Linux and macOS builds. You didn't need to make an issue for this 😉. I'm well aware...!

**Comment by afritz1** [comment]
Okay, it's out. Let me know if it works!
