### ISSUE TITLE
Deadlock in renderer on Linux (and rarely Windows)

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#145]
When in the game world, the game will randomly freeze on Linux. It appears to be a deadlock with one of the render threads. This behavior is strange because I haven't seen any deadlock issues on Windows with the same code.

Tested on Ubuntu 18.04 64-bit.

**Comment by afritz1** [comment]
Appears to not deadlock if only using one render thread (render threads mode = very low). Anything above that has a risk to freeze.

**Comment by Carmina16** [comment]
It froze for me on Windows once, with the default settings.

**Comment by afritz1** [comment]
Okay, it's probably a programming error then. I think it might've frozen for me too in Windows, but very rarely (i.e., once every other week).

**Comment by Translator5** [comment]
What time passed till it freezes?
For me everything works well, playing it for several minutes (~ 10 minutes), using default settings.

**Comment by afritz1** [comment]
On Ubuntu with 8 threads, usually anywhere from 2 seconds to a minute maybe. Can't really reproduce it on Windows with any thread count.

**Comment by Translator5** [comment]
> On Ubuntu with 8 threads, usually anywhere from 2 seconds to a minute maybe. Can't really reproduce it on Windows with any thread count.

Nope, for me it works fine - as I wrote, 10 Minutes without freezing.

**Comment by GregTheMadMonk** [comment]
For me, game seems to become playable even with max threads settings when I replace 
```
threadData.condVar.wait(lk, [&threadData, &data]()
{
	return data.threadsDone == threadData.totalThreads;
});
```
(line 6357 of SoftwareRenderer.cpp) with just
`threadData.condVar.wait(lk);`
Idk why yet

**Comment by afritz1** [comment]
I'm not sure. Maybe it's an issue with spurious wake-up that's causing a race condition within the `wait()` lambda (although the lambda there is _designed_ to guard against spurious wake-up). There must be a race condition somewhere or else the deadlock wouldn't happen.

I don't think the `threadsDone` variables need to be atomic, but maybe they do.

**Comment by afritz1** [comment]
I ran the GCC thread sanitizer on the engine and, while it found a couple data races (that turned out to be false positives, I'm 99% sure), it did not report anything when the software renderer froze. So I'm still stumped on this issue.

**Comment by afritz1** [comment]
Talked on Discord a bit about this, and it looks like a better idea would be to replace the existing multi-threaded rendering code with a different worker thread design.

**Comment by jdougharty** [comment]
Can confirm the same problem, but in windows 10. It would become unresponsive and never return after anywhere from 2 -5 minutes when displaying the world (including the entry dungeon). Dropping the thread option to very low seems to have fixed this as I've transitioned through multiple towns and dungeons without any issue since.

**Comment by afritz1** [comment]
I haven't had any deadlocks on Windows 10 for months. This threading bug is hard to pin down. Like I said above, I just need to re-design the render threads to be more like worker threads.

**Comment by Digital-Monk** [comment]
Do you use optimizations like GCC's `-ofast` on other builds?  Just wondering because when I read
```
-Ofast

    Disregard strict standards compliance. -Ofast enables all -O3 optimizations. It also enables optimizations that are not valid for all standard-compliant programs. It turns on -ffast-math, -fallow-store-data-races and the Fortran-specific -fstack-arrays, unless -fmax-stack-var-size is specified, and -fno-protect-parens.
```

What jumped out at me was `-fallow-store-data-races`, which just sounds bad if you're experiencing hard to find race/lock conditions.

Probably not the issue, but thought I'd toss it out there in case.  Multi-threading lock bugs are a pain.

**Comment by afritz1** [comment]
PR #199 appears to have fixed this. If anything comes up in the future, then this will be re-opened.
