### ISSUE TITLE
Implement chunk system

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#148]
In order for the engine to make the next leap forward towards matching the original game's behavior, the static voxel grid code needs to be replaced with a dynamic chunk system. This will allow wilderness generation to be implemented and, oddly, also the generation outside the perimeter of interiors and cities, as referenced in #129.

@Carmina16, judging by the Wilderness page in the wiki, there exists an absolute origin (0, 0) in the wilderness because it is 64x64 chunks, but what about cities and interiors? You wrote in issue #126 that the game treats cities, interiors, wilderness, dungeons, and main quest dungeons separately. This would help guide my implementation of a floating origin (something I am still learning).

Ideally I could replace 64-bit floats in the renderer with 32-bit floats because all renderable objects would be relative to the floating origin, which I'm currently envisioning as the chunk that the player is in.

**Comment by Carmina16** [comment]
The original engine uses a 128x128 block buffer, with the origin in the northweast corner. In wilderness, the game just shifts everything 64 blocks and slides 2 new wilderness levels in.

**Comment by afritz1** [comment]
>with the origin in the northweast corner

I'm going to assume you meant northeast! It is strange how the game generates seemingly infinite empty space outside the level for interiors though. That is why I was confused and assumed the game uses something more complex than that origin for interiors. The ceiling continues infinitely and the floor and main level seem to use some default value.

It is similar for exteriors but there seems to be some pattern to the floor. Maybe it's like how the wilderness uses a partial definition of the city for the `WILD00{0,1,2,3}.MIF` chunks. Cities supposedly use the floor of wilderness chunks to fill in the space behind the floating castle graphic at palace gates. That's my understanding at least, so I'm not sure how the game could use a 128x128 block buffer for cities.

**Comment by Carmina16** [comment]
It seems the buffer lookups for the floor texture is looped, so the block before (0,0) is (127,127), (1,0) -> (0,127) etc. The ceiling consists of a single texture, so nothing is looked up.

**Comment by afritz1** [comment]
Oh. That makes a lot of sense, I guess. I should be able to implement things this new way now, thanks.

**Comment by afritz1** [comment]
#200 is merged.
