### ISSUE TITLE
GLOBAL.BSA Layout

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#15]
WinArena is able to print out (among several other things) a list of all the files contained within GLOBAL.BSA, shown with their byte offset from the beginning as well as their size in bytes.

I removed the line numbers here for brevity, but the last entry (ZOMBIE6.CFA) is at index 2440, so there are 2441 items contained in GLOBAL.BSA using a variety of formats:

--- Offset ---- Size ---- Filename -----
0x000002 0x02E1 01AXE.CFA
0x0002E3 0x14D7 01BARATT.CFA
0x0017BA 0x2AE0 01BARWLK.CFA
0x00429A 0x04AD 01BAXE.CFA
...
0xFF1273 0x2BA4 ZOMBIE3.CFA
0xFF3E17 0x3266 ZOMBIE4.CFA
0xFF707D 0x37CD ZOMBIE5.CFA
0xFFA84A 0x0D6C ZOMBIE6.CFA

Perhaps the virtual file system can use this information to load chunks of GLOBAL.BSA into the program. I can also put the actual list into a parse-able format at some point.

**Comment by kcat** [comment]
Yep, I have the VFS parsing GLOBAL.BSA and can pull individual entries from it, as if they were files on disk. :) That's where the XMI files are for the MIDI music, so it'll be part of the pull request for music once I get it working (which is close).

**Comment by Ragora** [comment]
You might just be able to mmap individual sections of the data files as well. At least for the act of any necessary parsing or conversion operations that would produce a result memory buffer anyway.

**Comment by afritz1** [comment]
Great. I'll be committing some small changes in a while, such as changing all `<SDL2/SDL.h>` includes to just `"SDL.h"` as that's what the CMake website suggests [here](https://cmake.org/cmake/help/v3.0/module/FindSDL.html) (in the last paragraph).

`mmap` isn't compatible with Windows if I remember correctly.

**Comment by Ragora** [comment]
Windows has an equivalent to mmap: https://github.com/DraconicEnt/KGE/blob/develop/components/support/platform/windows/file.cpp#L19

**Comment by kcat** [comment]
I'm not too keen on mmap'ing it (through ```mmap``` or the Windows equivalent), personally. Although the individual files in the default BSA aren't very big, when mods can use their own BSAs it can potentially have pretty large files which would be wasteful to map into memory (e.g. FLACs, high quality video files).

Besides, the standard ```istream``` interface doesn't have a method to access the underlying memory map, so it'll still need to be read in through the read method anyway. I have a wrapper ```istream``` implementation that uses a normal ```ifstream``` on the real file, but constrains it to a portion of that file with a corrected offset (so 0 is the beginning of the given resource, and it won't read past the end of the resource).

**Comment by Ragora** [comment]
I wasn't talking about mapping the entire BSA. Once we know where everything is we can mmap individual portions.
