### ISSUE TITLE
actual status? 

### ISSUE THREAD

**Issue by Askmewho** [afritz1/OpenTESArena#154]
Hi!! whats the actual status of these? its completable?? thanks as always

**Comment by afritz1** [comment]
Hello. I'm currently focusing on low-level systems in the engine, like asset loading, wilderness generation, and rendering. There is very little gameplay code yet.

The Readme file details the current status of things: https://github.com/afritz1/OpenTESArena/blob/0b2091d3d5f69d5a95523fbd81c087a8d0f96f73/README.md

Also see the wiki for the current roadmap: https://github.com/afritz1/OpenTESArena/wiki

If you would like something in a playable state, see Daggerfall Unity or OpenMW.

Thanks for your interest.

**Comment by Askmewho** [comment]
Thanks afritx1, but  armhf linux doesnt have unity support :( thankssss to you for responding, closing
