### ISSUE TITLE
Incorrect formula

### ISSUE THREAD

**Issue by jfregnault** [afritz1/OpenTESArena#155]
In source file "ExteriorLevelData.cpp" at line 637, the formula for the destination index is currently => const int dstIndex = xOffset + ((z + zOffset) * gridDepth);
It should be => const int dstIndex = xOffset + ((z + zOffset) * gridWidth);

NB: since almost every MIF files have the same Width and Depth, this usually doesn't matter, but for a few cases (2 or 3 MIF files) these dimensions are different, which leads to bad result.

**Comment by afritz1** [comment]
Could you give some examples of where it looks wrong? I would like to be able to test the changes and I don't know where you are talking about in-game.

**Comment by jfregnault** [comment]
Hello, sorry for not beeing precise enough.

After more invetigations I found 5 MIF file having different Width/Depth : 42110737.MIF, TOWN5.MIF, TSBD11A.MIF, TSBD3A.MIF, VILLAGE5.MIF :
 - 42110737.MIF is used only for dungeon "Fortess of Ice" in Skyrim province
 - the 4 others are used to build cities/towns/villages

Therefore there would be 2 functions to fix IMO :
 - ExteriorLevelData::loadCity( ) at line 637
 - InteriorLevelData::loadDungeon( ) at line 92

I didn't check all of the cases, I just noticed this issue by chance in "Greenglade" town (in "Black Marsh" province). In my environment it appears that 35 cities/towns/villages have this issue (I can't tell for dungeons because I didn't follow your logic for dungeons).

BTW I'm not using your c++ code, I wrote a C# tool to generate all fixed places into Microsoft .X format (yes I know it's obsolete). My goal is not to rewrite the game as you do, but just to be able to easily watch main cities and dungeons in a modern 3D viewer...
Since the file formats explanations weren't enough to complete my tool, I started to read your source code in order to find inspiration (don't worry I always give credits when I post any results :) ).
I just fixed my code (in this case inspired by yours) and then the town looked alright
=> I attached 2 screenshots to show that.
![before-fix](https://user-images.githubusercontent.com/7416110/60770179-7ce0d400-a0d8-11e9-9d82-8bdf8244e7cf.jpg)
![after-fix](https://user-images.githubusercontent.com/7416110/60770181-85390f00-a0d8-11e9-8b87-10364627f665.jpg)

If you could just check at least this same town (Greenglade@Black Marsh) you should be able to check if the fix is also needed in OpenTESArena.

I hope this helps...

**Comment by afritz1** [comment]
Greenglade, Black Marsh looks fine to me. Interior levels are handled correctly too because the Fortress of Ice looks fine.

It may be a little confusing, but I chose to make the coordinate system have the X axis north/south and Z east/west to make sense in right-handed 3D but that made things less intuitive for top-down 2D, such as Z being aliased as Y in a Vector2.

**Comment by jfregnault** [comment]
If this issue doesn't show up in OpenTESArena then I'm glad to hear it, it's the only thing that matters...  you can close this topic (probably something on my side). Sorry for having you waste your time.

**Comment by afritz1** [comment]
No worries. If there's something else in the future then open another issue or make a comment on a commit.

**Comment by jfregnault** [comment]
Despite this topic is closed, I feel like adding one last comment: 
If you look at the call to "InteriorLevelData::loadDungeon()" from "InteriorWorldData::loadDungeon()", especially the 2 parameters "gridWidth" and "gridDepth".
These 2 values are previously calculated this way:
  - const int gridWidth = mif.getDepth() * depthChunks;
  - const int gridDepth = mif.getWidth() * widthChunks;

It looks like these 2 values are inverted.
It would explains why the formula in the called function works anyway ... 2 bugs cancelling each other ?

However these parameters are also used several more times in the rest of the called function, therefore the invertion should have more consequences ... that you don't seem to have. 
Weird.

**Comment by afritz1** [comment]
In the original game, +X is west and +Z is south, but in OpenTESArena, +X is north and +Z is east in order to make the right-handed coordinate system more intuitive. Width and depth are transposed. It confuses me on occasion but it has worked well enough so far. It just didn't make sense to me for X to increase going to the left. Not sure why the original devs did math that way.
