### ISSUE TITLE
Switch from OpenCL 2.0 to OpenCL 1.2

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#16]
In a recent commit I added some CL defines in [CLProgram.h](https://github.com/afritz1/OpenTESArena/commit/2bfd9d8f7f947872bc48240e097fd7b8bbc74891#diff-935e129aabb688f34ecd29716b39f4c8) for restricting the program to OpenCL 1.2 compatibility. The `<CL/cl2.hpp>` header is still in use for now, but it could be switched to `<CL/cl.hpp>` if need be.

This change is because of issues with Nvidia support for OpenCL 2.0.

**Comment by Ragora** [comment]
I could try building and see what happens.

**Comment by afritz1** [comment]
Okay. I'll keep it as it is now then. I've used OpenCL 1.2 on a computer with an Nvidia card before but not with OpenCL 2.0.
