### ISSUE TITLE
0.12.0 Linux package does not contain `opentesarena-<version>` directory

### ISSUE THREAD

**Issue by abelsromero** [afritz1/OpenTESArena#195]
Not a big thing, but the _targ.gz_ package for latest Linux version does not contain the `opentesarena-<version>` directory (windows package does have it).
The impact is that instructions in readme do not work as they are now: https://github.com/afritz1/OpenTESArena#linux-ubuntu-1604.

Linux package
![image](https://user-images.githubusercontent.com/5781153/104850945-48b3b980-58f2-11eb-9408-b513d0f68e58.png)

Windows package
![image](https://user-images.githubusercontent.com/5781153/104850953-5406e500-58f2-11eb-9052-45f69d072866.png)

**Comment by afritz1** [comment]
Oh. I think this is a minor difference with how the 7-zip shortcuts zip the directories. On Windows I right-click the folder and select `Add to "<...>.zip"` which puts it one folder deeper, but with the Linux build I go through `Add to archive...` to make the .tar and then gzip that.

When decompressing the .tar.gz, ideally I think I should be able to do `Extract Here` a couple times (one for the .tar.gz, another for the .tar), which means the Linux build should have that extra folder.

**Comment by afritz1** [comment]
Hmm, works fine doing `Extract Here` twice with the 0.11.0 .tar.gz, so must be something different I did for 0.12.0.

**Comment by afritz1** [comment]
Okay fixed. Thanks Abel.

**Comment by afritz1** [comment]
I realized the Readme does not show `-Linux64` after the filename. Will add that to have consistency across releases.

**Comment by abelsromero** [comment]
> Okay fixed. Thanks Abel.

Happy to help. The progress of latest version is amazing :tada:
