### ISSUE TITLE
Mountains are floating

### ISSUE THREAD

**Issue by ZeriBun** [afritz1/OpenTESArena#211]
![image](https://user-images.githubusercontent.com/31106594/123187252-135f5900-d49a-11eb-98de-fbc2c25b7eed.png)

As you can see, mountains are floating.
Seems to be the case in lots of places. havent seen nonfloating mountains
(edit: easiest way to replicate is spawning into imperial city, then disabling collision, turning around and going through the wall, then look east there is a mountain)

![image](https://user-images.githubusercontent.com/31106594/123187746-0131ea80-d49b-11eb-8958-acf1ed21279a.png)
dont even know if this is supposed to be a mountain
(edit: theres far away houses infront of the mountain that are fogged out, thats why it looks weird. no bug here)

**Comment by Thunderforge** [comment]
Thanks for reporting this bug! Is there a particular location where this can be easily reproduced?

**Comment by ZeriBun** [comment]
you can noclip out of any cities walls, but without cheats you can go to cities that have unwalled sections like Southpoint in Valenwood

**Comment by afritz1** [comment]
Possible solution for this is to have the engine calculate how tall a texel in an Arena mountain texture is in degrees, then move the projected vertices down by that much so it still works in case textures are able to be modded to have any resolution. This all rests on the assumption that the original game does indeed shift mountains down by a pixel.

**Comment by afritz1** [comment]
A quick look through MOUNT000.IMG through MOUNT022.IMG shows that they in fact don't have a 1 pixel gap at the bottom like I originally thought, which is weird because I was so sure about that. So it could just be a renderer bug.

**Comment by afritz1** [comment]
The volcano in Morrowind does however (VOLCANO1.DFA and VOLCANO2.DFA), so that is one place with the gap.

TEMP10.IMG has a gap.

**Comment by afritz1** [comment]
This still happens in the new renderer but this issue can be closed. Reason:

The engine works like Minecraft - there is a set of loaded chunks around the player. The player's camera is some height above the ground and will be able to peer over the edge of the world pretty easily if there aren't that many chunks:
<img width="1920" alt="screenshot0000" src="https://github.com/afritz1/OpenTESArena/assets/6729557/9da7169e-911e-442d-852d-024dff3781db">

The solution is to have more chunks so they stretch further out to the horizon and the perceived gap between the world edge and distant land shrinks (although performance is bad right now):
<img width="1920" alt="screenshot0001" src="https://github.com/afritz1/OpenTESArena/assets/6729557/9136be5e-1b9f-45b2-be59-f12d967f9da3">

I guarantee the meshes for all distant lands have their bottom edge resting on Y=0, and the rasterizer samples the center of pixels, so there is definitely no rounding or off-by-one problem happening here.
