### ISSUE TITLE
Rename default branch from master to main

### ISSUE THREAD

**Issue by Thunderforge** [afritz1/OpenTESArena#214]
For the last nine months or so, GitHub has made `main` the default branch instead of `master`, and other Git hosts have done the same (more info [here](https://github.com/github/renaming)). Regardless of one's feelings on whether or not the change was necessary, it has become the new industry standard, and I think OpenTESArena should match it.

GitHub provides [a simple means to rename the default branch](https://docs.github.com/en/github/administering-a-repository/managing-branches-in-your-repository/renaming-a-branch#renaming-a-branch). This will automatically re-target any outstanding PRs to the `main` branch and will notify contributors to update their local clones (a full list of what it does can be found [here](https://github.com/github/renaming#renaming-existing-branches)).

We will also need to confirm that CI is pointed to the new `main` branch.

**Comment by afritz1** [comment]
Yeah we should do it as long as it doesn't break or otherwise mangle any of the Git history.

**Comment by Thunderforge** [comment]
It shouldn't break or mangle any of the Git history.

Since Git branches are technically just pointers to commits, all we're doing is creating a separate branch pointed to the same commit, and then telling GitHub that's the default one.

**Comment by afritz1** [comment]
I'd feel more confident about it after I merge my `text-rendering-redesign` branch, which could be a couple weeks still (don't know for sure). But I like the idea.

Git is a weird name to begin with ("an unpleasant or contemptible person" based on Google), so any improvements in the names of things associated with it are reasonable I think.

**Comment by Thunderforge** [comment]
> Git is a weird name to begin with ("an unpleasant or contemptible person" based on Google)

[According to Wikipedia](https://en.wikipedia.org/wiki/Git), it was intentional:

> Torvalds sarcastically quipped about the name *git* (which means "unpleasant person" in British English slang): "I'm an egotistical bastard, and I name all my projects after myself. First 'Linux', now 'git'."

**Comment by abelsromero** [comment]
I've renamed a few projects in GitHub and only issue is CI and any script that uses branch names.
About PRs there's no issue, in fact GitHub will notify users with open PRs and take care of repointing them.

**Comment by afritz1** [comment]
Should be all done. I verified in my Windows Subsystem for Linux and am about to on my Raspberry Pi.
