### ISSUE TITLE
A Question about the capablities of OpenTESAreana

### ISSUE THREAD

**Issue by springheeledjack66** [afritz1/OpenTESArena#224]
Hi, I'm a game development student and I've been looking to do projects outside of college and to network with people both professional and hobbyist, as such I wished to know if OpenTESArena is a suitable game engine to produce an original game project.

**Comment by afritz1** [comment]
It's just for TES: Arena and maybe Terminator: Rampage some distant point in the future. Not trying to be general-purpose in the way OpenMW is.

If you're interested in helping then find an issue here that interests you! Unfortunately there's not much low-hanging fruit though. I'm going to be focused on the renderer for a couple more months probably. Good luck!
