### ISSUE TITLE
Switch to GitHub Actions

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#235]
Travis CI hasn't worked for a long time and GitHub Actions looks like a good replacement.

`.travis.yml` and the `CI` folder can probably be deleted? Not sure if `.github/workflows/cmake.yml` is the only file needed now.

Need to add the SDL2/OpenAL Soft/WildMIDI dependencies to `cmake.yml` so it configures correctly.

**Comment by Allofich** [comment]
> .travis.yml and the CI folder can probably be deleted? 

Those were only for Travis CI, so it should be fine to delete them if you are migrating to GitHub Actions.

**Comment by Allofich** [comment]
Of course it might be helpful to keep them around as a reference until the GitHub Actions are building successfully.

**Comment by Allofich** [comment]
To get the current `cmake.yml` file working (Linux build), add a new step before the "Configure CMake" step to install the dependencies, like

```
name: Install dependencies
      run: sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libopenal-dev
```

The name "Install dependencies" is just a name I chose, I think it can be anything. The above doesn't include WildMIDI, so the build will be without it. To get it, too, you can use the following instead:
```
name: Install dependencies
      run: |
           sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libopenal-dev
           wget https://github.com/Mindwerks/wildmidi/archive/master.zip
           unzip master.zip
           pushd wildmidi-master && mkdir build && pushd build && cmake .. && make && sudo make install && popd && popd
```

**Comment by afritz1** [comment]
Looks like that worked. Thanks Allofich! Just the Linux build is fine for now.
