### ISSUE TITLE
Very slow performance

### ISSUE THREAD

**Issue by lrustand** [afritz1/OpenTESArena#246]
Is this actually playable for anyone else? Because for me I get roughly 1 fps, and it is constantly using 100% of a single CPU thread. Even the mouse pointer is super sluggish. I have tried experimenting with the render threads setting, but no matter what I set it to the game still only uses one thread. I have a pretty decent relatively new i7 so I would expect to be able to play this with a very high fps.

**Comment by i-am-the-gabe** [comment]
From what I understand, this is not yet playable and it's still under heavy development (a new renderer is in the works from what I've seen on the Discord). You're right to assume this is due to (mostly the renderer) being single threaded: see #245 which sets up some of the groundwork for actually making proper use of threading.

**Comment by Liebranca** [comment]
Oh, trying to run a 1994 DOS game, are you? Gonna need sixteen cores for that... at the very least ;>

You can play the original single threaded on a piece of crap budget rig and performance will be OK. That's your best bet while Harun figures out new ways to make the minimum specs of Arena compete with Crysis.

**Comment by afritz1** [comment]
Part 1 of the renderer redesign was merged recently. The objective is to reach visual parity with Arena, then optimization work will follow. Feel free to connect up a profiler to see what's causing the low fps. I don't specialize in renderer optimization, just trying to get things working reliably.

**Comment by abelsromero** [comment]
Only out of curiosity, I know the current rendering is still experimental, but I saw the announcement on Twitter about the completion and I am wondering what's the expected performance, and if there's a way to get some measurements (obviously mangohud won't work on CPU render). I am running and AMD 3700X and compiling with `ReleaseNative` it did not run really well. I noticed 1 core getting 100% though.

**Comment by afritz1** [comment]
Still working through a couple lighting and shading bugs before I focus on optimizations. I haven't touched the triangle clipping or rasterizer yet but would love to make improvements there. 1 core is still the only option.

**Comment by afritz1** [comment]
Merged part 3 of the renderer work today. It's properly multi-threaded again and performance is better, about 1080p60 on my Ryzen 7950x. Obviously a GPU renderer would be 5x faster but that wasn't the point with this. I would need a rendering expert to get more FPS out of it.
