### ISSUE TITLE
Identical WildMidiSong::read() branches

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#25]
The two `LIBWILDMIDI_VERSION` [branches](https://github.com/afritz1/OpenTESArena/blob/3cc1aeef998a0fd30691b97429fce836bf0234ef/OpenTESArena/src/Media/WildMidi.cpp#L51) in `WildMidiSong::read()` seem to do the same thing. Are they intended to be different in the future?

**Comment by Ragora** [comment]
It looks like it is to try and deal with slightly different API signatures between some version threshold of WildMIDI. Probably just a compat thing, as in my case the latest official WildMIDI version I can get from my package repos is 0.2.3.

**Comment by kcat** [comment]
> The two LIBWILDMIDI_VERSION branches in WildMidiSong::read() seem to do the same thing. Are they intended to be different in the future?

It's actually using two different pointer types. Before 0.4 (or maybe 0.3.9, I'm not sure when the change was), it expects a ```char*``` buffer to write to, but the newer versions expect ```int8_t*```, aka ```signed char*```. It's an interesting quirk of C and C++ that ```char``` is considered distinct from ```signed char``` and ```unsigned char```, so a pointer to one will not auto-cast to the other, even though ```char``` will be signed or unsigned.
