### ISSUE TITLE
Game world palette documentation

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#251]
I'm trying to render the world a more historically accurate way now. It seems that Arena modifies parts of the active palette to achieve various effects like sky gradient, nighttime, and thunderstorms, although I don't understand all of it yet. I do know that it uses NORMAL.LGT and FOG.LGT for light levels.

PAL.COL:

![PAL.COL](https://github.com/afritz1/OpenTESArena/assets/6729557/d2df40a5-9c47-4454-9b05-b3f6cd0fcb69)

I'm expecting some range of 6 colors in here to come from DAYTIME.COL and be written to for each time of day for the sky gradient.

If any of these descriptions are wrong, let me know below, and once all 256 colors are documented then I'll copy it to the wiki.

Row 1:
- 0: black for opaque, transparent for alpha-tested
- 1-13: light levels, used with ghosts and clouds
- 14,15: ghost eye lookup colors pointing to index 158,159

Row 2-7: general-purpose gradients (some used with water, fireballs, portrait background?)

Row 8 (starts with black-white-white-black):
- 0: dry chasm wall color and building windows during daytime
- 1: building window color lookup, points to index 97 or 112 depending on time of day
- 2,3: unknown
- 4-13: general-purpose gradient
- 14,15: general-purpose gradient

Row 9-15: general-purpose gradients (some used with portrait backgrounds?)

Row 16:
- 0-10: general-purpose gradient
- 11: unknown
- 12,13: text color
- 14,15: unknown

**Comment by afritz1** [comment]
Saw this in the Weather page of the wiki for thunderstorm sky colors:
> `flash_colors` is a 3-byte array `@43602`

**Comment by afritz1** [comment]
Several of the full-bright colors are used with temple windows (at least magenta, blue, green, forest green, fire).

**Comment by Carmina16** [comment]
The game uses the fraction of a day (6 to 18 hours) in 0..255 range to copy 8 consecutive values from `DREARY/DAYTIME.COL` into indices 1..9 of the VGA palette, and uses `DITHER/DITHER2.IMG` to draw the sky gradient.

**Comment by afritz1** [comment]
Thanks, I'll look at it tonight.

**Comment by Carmina16** [comment]
Ghosts are using the special indices in their bitmaps, but when drawing to the screen, the real colors from light tables are used.

**Comment by afritz1** [comment]
Oh right. I'm doing that in the pixel shader but just didn't put two and two together. It's exciting doing shading this more classic way instead of mixing and matching methods like I did in my true color renderer.

**Comment by afritz1** [comment]
Is there extra work done with the two dither textures before putting sky pixels? They are 16x50 and it looks like the first 8 columns have a different pattern than the other half.

I'm also wondering about the darkest light level for lights. I'm using NORMAL.LGT and FOG.LGT but they do not reach pitch black like Arena. Does Arena make a 14th row that's just one solid color for all 256 colors?

**Comment by Carmina16** [comment]
* Dither textures are 8x100 and probably are columns of pixels to fill the upper half of the screen.
* Windows are black on clear day, rgb(136,136,148) during the fog, and rgb(255,164,0) during the night. During twilight (`x <- fGameHour*1024`=256..271 and 753..768) their values come from a VGA RGB array `@4315a` with 16 elements; the index is (`x`-256) and (768-`x`) correspondingly. The corresponding water light levels are in a corresponding word array `@4313a`

**Comment by afritz1** [comment]
Thank you, I'll try to get through these today.

**Comment by afritz1** [comment]
Yes the dither textures should've been 8x100. I think 16x50 came from a much older project.

Also, in my previous renderer from 0.14.0 the sky was just a rectangle on the screen but now it is a mesh like a circus tent - cylinder with a cone on top. I know you recorded how star rendering works with the 64/255 intensity limit and I want to do that today too. <img width="1920" alt="screenshot0000" src="https://github.com/afritz1/OpenTESArena/assets/6729557/2914c2de-d41c-4286-b3e3-eddc80ba9617">

**Comment by afritz1** [comment]
I got window colors working just now and everything else (thunderstorms, sky gradient) is in. Thanks Carmina16.
