### ISSUE TITLE
Revise Readme to prioritize obtaining game files from Steam

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#255]
In #243 it sounds like reading Steam paths and config files should be the default way forward for loading game files on all platforms. Downloading Arena from the Bethesda website or GOG should be fallbacks.

**Comment by Thunderforge** [comment]
In terms of raw numbers: Steam users > GOG users > Bethesda website visitors, at least for the entire platform. We obviously aren't privy to exact numbers for Arena, but it's reasonable to assume that this will be reflected for that game.

For that reason, I think it's reasonable to reorder the Readme to match that order.

Long-term, it would be great to have the game auto-check the typical install locations for Steam & GOG and suggest the user to pick one of of them if found, or give them the option to pick another install location. My recollection is that [OpenRA](https://www.openra.net) does this. But that's beyond the scope of this issue.

**Comment by Thunderforge** [comment]
Question: do we still want the instructions on the Readme page? Or do we transfer to the wiki?

**Readme**
* Pros
** Easy to find
** History is tracked in Git
** Able to be improved by PRs
* Cons
** Makes a long Readme even longer
** More difficult to find the exact instructions
** No table of contents

**Wiki**
* Pros
** Avoids lengthening the Readme
** Having its own space makes it easier to read and have multiple sections
** Includes table of contents
* Cons
** Will likely require a link from the Readme
** History is not tracked in Git
** Cannot be improved by PRs; need special permission

**Comment by afritz1** [comment]
The Readme should be more gamer-friendly and less technical. Technical details should be in the wiki. Maybe the Readme could have the "easiest install" instructions, like just Steam, and the wiki would have GOG and Bethesda links. Just a thought.

**Comment by afritz1** [comment]
I changed the Windows part of the Readme to Steam-only. I'll revise again once ArenaPath has been changed to ArenaPaths in code.
