### ISSUE TITLE
~WildMidiSong() causes heap corruption

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#26]
The PERCNTRO.XMI music can be heard on startup, but upon clicking "Start New Game", "Exit", or the "X" to close the application, Visual Studio breaks in the ~WildMidiSong() [destructor](https://github.com/afritz1/OpenTESArena/blob/3cc1aeef998a0fd30691b97429fce836bf0234ef/OpenTESArena/src/Media/WildMidi.cpp#L42).

~~Could this be a WildMIDI issue with closing .xmi files?~~ I am using WildMIDI 0.4.

**Comment by Ragora** [comment]
I'd debug it if my anything worked. I'm running the same WildMIDI version but the playback still doesn't work.

**Comment by afritz1** [comment]
Is your soundfont path in `options.txt` set correctly? I'm using the freepats .zip package from [here](http://freepats.zenvoid.org/).

**Comment by Ragora** [comment]
Looks like it's probably working now, just ran into the issue from #24 though. Time to fix that assertion!

**Comment by afritz1** [comment]
If I comment out `WildMidi_Close(mSong);`, then the program runs like normal and plays the music as intended, but it's obviously not closing the MIDI tracks then. I wonder if this could be at all related to using a newer MSVCR__.dll than @psi29a's recommended MSVCR80.dll for WildMIDI (since MSVCR80.dll is intended for Visual Studio 2005).

**Comment by Ragora** [comment]
I would see where it is breaking. You should be able to at least see what binary blob it halted in (a DLL name in the call stack or something).

**Comment by afritz1** [comment]
Well, I was able to build wildmidi_dynamic.dll and its associated debug files, and after putting them in the OpenTESArena library folder, the program doesn't have any trouble anymore with WildMIDI. Strange.
