### ISSUE TITLE
Compiling issues, what are the correct settings for ARM64 V8?

### ISSUE THREAD

**Issue by Chatplosion** [afritz1/OpenTESArena#264]
Dear developers and contributors,

something is very hard to understand for me.

I use Ubuntu 24.04.1 LTS with Kernel 6.6.0-odroid-arm64 LTS on Odroid N2L 4GB running at 2xARM Cortex-A53 @ 2200Mhz, 4xARM Cortex-A73 @ 2556Mhz and Mali G-52 6EU @ 1Ghz.

The gui driven cmake is not able to select automatically working settings.
In most cases cmake can find everything by itself, but this is different. I believe that other ARM or Apple M1 and M2 can be affected, too.
It doesn't make sense that any AVX, AVX2, F16C, SSE4_1, SSE4_2 are marked, because they are technically not implemented.
About LZCNT and TZCNT, I can't find something about support or not implemented.
ASSERTS and STD_VECTOR are in most cases working and universal.
ARM V8 should have a FMADD.
But for what is USE_WASM_SIMD for?
I have seen that in some cases SIMD can execute SSE based code.

What shall I select to get a compilable configuration?

Linux makefile always fails, because lack of memory.
Ninja makefile has the same problem.

Sometimes I read something of 64 serial jobs of LTO-wrapper.

My system crashes with a black screen of nothing/death.

Am I just not qualified enough?

**Comment by afritz1** [comment]
Even if you get the engine working, that device will probably run it at single digit FPS, so just have low expectations. When I compile on my Pi 4 I don't need to disable those vector instructions because Jolt knows they don't apply to ARM. I think I just do
```
mkdir build-releasenative
cd build-releasenative
cmake .. -DCMAKE_BUILD_TYPE=ReleaseNative && make -j4
```
If make runs out of memory then maybe set `-j2` instead of 4.

**Comment by Chatplosion** [comment]
At previous versions, I got 10 FPS at full screen wit maximum 49% CPU usage. An Odroid can outrun near to every Raspberry PI variants.
The main issue is driver development at a low pace and insufficient support from Amlogic.
Even the use of Wayland instead of X and GLES instead of GL can give speed advantages.
GZDoom is running Doom 2 at up to 120 FPS at 1920x1080 scaling and full visual enhancement features.
It must be compiled with -j1 just to prevent the compiler from failing!
For Arm64 systems should be considered that compile could need up to 300% of memory with c++ compared to x86-64.
The next interesting part is why does a ReleaseNativeNoLTO option not exist?

**Comment by afritz1** [comment]
ReleaseGenericNoLTO was added for faster compilation than ReleaseGeneric but more optimized than Debug so I can work faster. ReleaseNativeNoLTO wouldn't be as useful because ReleaseNative's purpose is maximum optimizations for the computer compiling it.

**Comment by afritz1** [comment]
I haven't used Jolt long enough to know, I just use the defaults. It's a work in progress, I know performance is not great.
