### ISSUE TITLE
Suddenly Force close

### ISSUE THREAD

**Issue by ZackyC** [afritz1/OpenTESArena#266]
hi, running program on windows 10 when start to launch otesa.exe suddenly close and exit whitout warning
![opentesa bug](https://github.com/user-attachments/assets/177a55eb-2936-443a-9f8f-e9eebfda6e59)
log file create nothin

**Comment by afritz1** [comment]
Try updating your Microsoft redistributable https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads, use the X64 option in the table.

**Comment by ZackyC** [comment]
can confirmed is working now, let wait for real gameplay, sorry for asking but its only me or project milestone is missing for next update?

**Comment by afritz1** [comment]
Next milestone should have some gameplay
https://github.com/afritz1/OpenTESArena/wiki#0160-minimum-playable-starting-dungeon-collision-detection-and-core-stats
