### ISSUE TITLE
Doxygen

### ISSUE THREAD

**Issue by Ragora** [afritz1/OpenTESArena#3]
Mostly a suggestion as projects can easily get to a point where inline documentation would be vastly helpful, and the commenting format Doxygen requires is pretty natural so there's the added side benefit of being able to generate HTML documentation from your programming. 

This issue can basically just be summed up as "header documentation", really. At the least, requiring the use of Doxygen compatible comments standardizes the code a little bit more. I'm also just personally obsessed with documenting the crap out of everything I write.

[Here's a pretty decent example of it in action.](https://github.com/DraconicEnt/KGE/blob/develop/components/support/include/support/SSettingsRegistry.hpp)

**Comment by afritz1** [comment]
I've seen Doxygen used by a big project before; namely, the physically-based renderer [pbrt](https://www.csie.ntu.edu.tw/~cyy/courses/rendering/pbrt-1.04/doxygen/html/hierarchy.html). I haven't used it myself yet, but standardizing comments in this project sounds like a great idea. I'll see about starting to add conforming comments to the code soon.

**Comment by Thunderforge** [comment]
Which document style do we want to use in this app? It looks like several are [supported in Doxygen](https://www.stack.nl/~dimitri/doxygen/manual/docblocks.html)

**Comment by afritz1** [comment]
I think using `//!` for single-line comments is the most intuitive for me. I haven't gotten around to this issue because I've just been solving other problems in the meantime.

**Comment by Thunderforge** [comment]
I assume that means that multi-line comments look like this then:
```
/*! 
 * A longer block
 */
```
I asked because I was interested in adding some documentation to a few classes and was unsure about the preferred style.

**Comment by afritz1** [comment]
Hmm, maybe use
```
//! Description for a class method
//! that needs to be multi-line.
```
I haven't tried it in practice yet but I think that's how I would do it. I don't really use `/* */` anywhere in the code on a regular basis, so the double forward slash + exclamation mark would be the go-to option.

I assume these styles would take some experimenting with before the most convenient one becomes evident.

**Comment by afritz1** [comment]
Decided not to use Doxygen or any doc generation yet. Will re-evaluate this if there's enough demand.

(also this is nearly a 7 year old issue, whoops)
