### ISSUE TITLE
Some IMG files have erroneous black pixels.

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#32]
A small portion of IMG files, like `LABRINTH.IMG`, have some black pixels scattered around where they should not be. Could this be from `char` overflow?

**Comment by kcat** [comment]
No, it seems the output history used for type 4 and type 8 decoders need to be set to ```0x20``` instead of ```0```.

**Comment by afritz1** [comment]
Alright. The changes were applied in pull request #33.
