### ISSUE TITLE
References to Types that Don't Benefit

### ISSUE THREAD

**Issue by Ragora** [afritz1/OpenTESArena#4]
There's a lot of references to data types being returned and passed as arguments where there's no real benefit to actually using a reference. For example, the int:

> Entities/DerivedAttribute.h:    const int &getMaximum() const; // Might be a calculated value instead of a member in the future.
> Entities/Entity.cpp:const int &Entity::getID() const
> Entities/CharacterClass.cpp:const int &CharacterClass::getStartingHealth() const
> Entities/CharacterClass.cpp:const int &CharacterClass::getHealthDice() const
> Entities/DerivedAttribute.cpp:const int &DerivedAttribute::getMaximum() const
> Entities/Entity.h:      const int &getID() const;
> Entities/PrimaryAttribute.cpp:const int &PrimaryAttribute::get() const
> Entities/PrimaryAttribute.h:    const int &get() const;
> Entities/Player.h:      const int &getPortraitID() const;
> Entities/Player.cpp:const int &Player::getPortraitID() const
> Entities/CharacterClass.h:      const int &getStartingHealth() const;
> Entities/CharacterClass.h:      const int &getHealthDice() const;
> Interface/ListBox.cpp:const int &ListBox::getScrollIndex()
> Interface/ListBox.h:    const int &getScrollIndex();
> Game/Year.cpp:const int &Year::getEraNumber() const
> Game/Year.cpp:const int &Year::getYearNumber() const
> Game/Options.cpp:const int &Options::getScreenWidth() const
> Game/Options.cpp:const int &Options::getScreenHeight() const
> Game/Options.cpp:const int &Options::getSoundChannelCount() const
> Game/Date.cpp:const int &Date::getDayNumber() const
> Game/Year.h:    const int &getEraNumber() const;
> Game/Year.h:    const int &getYearNumber() const;
> Game/Options.h: const int &getScreenWidth() const;
> Game/Options.h: const int &getScreenHeight() const;
> Game/Options.h: const int &getSoundChannelCount() const;
> Game/Date.h:    const int &getDayNumber() const;
> Rendering/Texture.cpp:const int &Texture::getWidth() const
> Rendering/Texture.cpp:const int &Texture::getHeight() const
> Rendering/Texture.h:    const int &getWidth() const;
> Rendering/Texture.h:    const int &getHeight() const;
> Rendering/TextureReference.cpp:const int &TextureReference::getOffset() const
> Rendering/TextureReference.cpp:const int &TextureReference::getWidth() const
> Rendering/TextureReference.cpp:const int &TextureReference::getHeight() const
> Rendering/TextureReference.h:   const int &getOffset() const;
> Rendering/TextureReference.h:   const int &getWidth() const;
> Rendering/TextureReference.h:   const int &getHeight() const;
> World/VoxelReference.h: const int &getOffset() const;
> World/VoxelReference.h: const int &getTriangleCount() const;
> World/VoxelReference.cpp:const int &VoxelReference::getOffset() const
> World/VoxelReference.cpp:const int &VoxelReference::getTriangleCount() const
> 

There's no gain on 32bit machines because internally these will be passed as a 32bit pointer anyway.  On 64bit machines there's actually a 4 byte loss since we'd be passing a 8byte value around to reference a 4byte value that we never actually want to modify (as explicitly declared by its const-ness). In both of these cases we have the slight performance detriment of an extra pointer deference, so overall its worthwhile to just pass these types around as regular values on x86 and x86_64.

**Comment by afritz1** [comment]
Yes, I am aware that a `const int&` takes up more space than an `int` on 64-bit. The usage of it in my code is a result of my somewhat academic bias on C++, in that I want to emphasize the intended semantics of the returned object. Whenever I see a const reference returned, I know for sure it's either a class member or something in global memory that lasts longer than the method call, instead of a result of an expression for example.

Whether changing them all to `int` is worth the slight change in performance, I can't say. Since they're getters anyway with const-qualification, I'd say changing it to `int` was okay.

See my C++ [coding guide](https://github.com/afritz1/OpenTESArena/blob/master/Coding%20Guide.md) for what I've learned about in modern C++ in the past year and a half (that's how long I've been doing C++).

**Comment by Ragora** [comment]
It's likely not worth the difference, but it's also a pretty easy thing to implement as well. As far as semantics go, you can still return a const a value, but at that point it doesn't really matter. The const-ness *really* only matters if actually writing to it will cause later problems.
