### ISSUE TITLE
FLIC File Decoding

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#54]
The cinematic sequences (opening scroll, Ria Silmane, etc.) are currently black because the FLIC frame decoding is not complete. I took a shot at it, but if someone else knows more about FLIC files, then please take a look.

The public methods for the `FLCFile` class have been defined, so only [FLCFile.cpp](https://github.com/afritz1/OpenTESArena/blob/26a39033a0d34f681e27f85dd6a08cb2835ff7e8/OpenTESArena/src/Assets/FLCFile.cpp) needs to be worked on. Each `unique_ptr` in the `pixels` member is created after decoding each frame, and each should point to a complete frame of the video.

Refer to any of the other image classes (.CIF, .IMG, .SET, etc.) for general style guidelines.

**Comment by afritz1** [comment]
Fixed in commit https://github.com/afritz1/OpenTESArena/commit/be0fc945fbc5081f273d2b5e3442d85151e13e9d.

**Comment by Allofich** [comment]
Great to hear you were able to get past this roadblock!
