### ISSUE TITLE
Cursor scale

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#70]
The default cursor scale in the Options.txt file is 2.0, which makes a pretty small cursor. I found that a value of 3.6 seems to recreate the size of the cursor in the original game. Personally I like this size because it fits with the pixel size of the rest of the graphics. You might want to make this the default or at least comment on it in the file, like you do for how to recreate a 4:3 aspect ratio.

**Comment by afritz1** [comment]
The cursor scale code is basically a rough draft. I don't think its size is currently relative to the window. I haven't decided on a good way to implement it, so right now I just leave it as an option for users to modify in the options.

**Comment by Allofich** [comment]
All right. Also, I know that in the Daggerfall Unity forum, they had some high-res tool tips that were added to the game that I didn't think looked that great because they clashed with the low-res graphics, but people there were saying they liked it, so this is just a matter of taste. I just wanted to let you know that 3.6 seems to recreate the original cursor size.

**Comment by Allofich** [comment]
Anyway that will probably be it from me for a while. Thanks for your responsiveness, it makes it fun to work together, and I hope you didn't feel like I'm intruding too much! Feel free to change things back or whatever if you want.

**Comment by afritz1** [comment]
Yeah, no problem! Doing things myself is nice because I have a better mental model of the program, but when others point out some potential changes, it's nice to read through them and discuss the options. I might shift towards making up little tasks for people to do in the future, but I just haven't done that yet because I still prefer being the lead programmer and it's a hobby project.

**Comment by afritz1** [comment]
I added cursor scale to the options menu in commit a97b45b8bf40e11a0695e46a56529fd00b068646, so users can tweak it and see the results right away. I might decide to add tooltips to some options as well, so it can show suggestions like setting the cursor scale to 3.6.
