### ISSUE TITLE
Feature: Add an option to start the game with a random character, skipping menus

### ISSUE THREAD

**Issue by Thunderforge** [afritz1/OpenTESArena#78]
OpenMW has a very useful [command line argument](https://wiki.openmw.org/index.php?title=Testing#Game_Arguments) to start the game in such a way that skips the menus and drops you straight into a default cell with a default character. This is a pretty useful tool and would be helpful for OpenMW as well to quickly test new gameplay functionality, and would be a welcome addition as well.

**Comment by afritz1** [comment]
I've definitely considered this, but I just haven't gotten to it. I'll see about adding it soon.

**Comment by afritz1** [comment]
Added in commit a31b0f326cd7a8a30563f44b381aa3625ac7044d.
