### ISSUE TITLE
DRUMS.VOC doesn't repeat

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#92]
Sound triggers don't always fire in original Arena, but they do in OpenTESArena. I tested with the drip sounds in the starting prison cell.

**Comment by afritz1** [comment]
I was wondering about this. I think it's because of Arena only playing one sound at a time that's making you think the sound triggers don't always fire (i.e., because of the player's steps). The .INF files have a `~` at the beginning of text triggers to denote which ones are played only once, but there's nothing like that for sound triggers.

**Comment by Allofich** [comment]
I did a little more testing of original Arena.

- I confirmed that other sounds (footsteps, weapon swing, etc.) and the sound triggers play on the same channel, so you can't two at the same time. I think you already knew this.
- I tried multiple times but could never get the drum sound on the tile immediately outside of the starting cell (with the message about the twisted corridors) to play
- The drum sound on the nearby tile that gives the text about resting in the niches plays 11 times in a row when triggered. In OpenTESArena it only plays once. I tried three times in a row and each time it was 11.

I know a drum sound also plays in StoneKeep. I'll go test how many times that one plays.

**Comment by Allofich** [comment]
The StoneKeep drum sound also played 11 times. Also I got the sound with the "twisted corridors" message to play by tapping the up arrow to inch forward and make sure the footstep sound didn't block out the triggered sound. This drum effect also played 11 times.

I similarly inched forward into one of the drip sound triggers, and it played 15 out of 15 times, so I think you're right that it was just being prevented by playing due to footstep sounds.

So, since the only thing that seems to be "wrong" at the moment is the number of times the drum plays, I'll change the issue title.

**Comment by Allofich** [comment]
If the "play 11 times" data for the drum sound is in the sound file itself, for example, than I suppose this issue title is maybe still inaccurate. But I'm sure you get the idea.

**Comment by afritz1** [comment]
Ah, sorry you had to go through all that. See my comment [here](https://github.com/afritz1/OpenTESArena/blob/b35d33fb6af40b83331083d0049f71cf5de4f0da/OpenTESArena/src/Assets/VOCFile.cpp#L101) in `VOCFile.cpp`.

`DRUMS.VOC` is the only sound file with repeating data, and that functionality just hasn't been implemented yet. I also figured that if OpenTESArena was going to allow the playing of multiple sounds at once, then if multiple instances of `DRUMS.VOC` were playing, it would sound _really_ obnoxious. Maybe it could be an option to have it use the repeated data.

**Comment by Allofich** [comment]
Oh well, so I guess this was all just confirmation of stuff you already knew.

> Maybe it could be an option to have it use the repeated data.

Another idea is to only allow a particular sound to play once at a time. But you might want, for example, drip sounds to be able to overlap slightly, so maybe only apply this check if the sound is being repeated, which would mean DRUMS.VOC only I guess.
