### ISSUE TITLE
Clang warnings and adding macOS to Travis CI

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#93]
I've noticed that the project is keeping very clean compile logs in Travis-CI GCC builds, and also when building in Visual Studio. I decided to test running it with clang enabled, and quite a few warnings popped up.

https://travis-ci.org/Allofich/OpenTESArena/jobs/323518887

It may be worthwhile to double as a light review of your code, maybe you'll see some other things you'd like to fix up while addressing these.

If you want to add clang as a compiler from here on, you can simply add it to the "compiler" option in the travis.yml file.

I also looked at adding OS-X builds, but it looks like a little work would be required to figure out how to get the dependencies correctly. Just adding OS-X to the travis.yml file, it will fail due to OS-X lacking the apt-get command.

On https://docs.travis-ci.com/user/installing-dependencies/, it explains how to set this up by OS. The example is:
`install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install foo; else brew install bar; fi`

and I was able to get past the error using this. But then, it still failed to download the dependencies. so we'd need to set it up to get appropriate OS-X dependencies. If it was all set up, in addition to adding another layer of checks on the code, it would be a step toward closing https://github.com/afritz1/OpenTESArena/issues/74.

**Comment by afritz1** [comment]
Yeah, having it compile on both GCC and Clang would be objectively better I think.

I looked through that Travis CI log and all of the warnings are relatively benign, but I'll fix them anyway. I guess Clang is just a little more strict about some things like explicitly overriding pure virtual functions with other pure virtual functions.

We can get Travis CI to compile for macOS at some point, too.

**Comment by Allofich** [comment]
Looks like all the Clang warnings are gone!

As for macOS/OS-X, is there anyone using or familiar with it? @Thunderforge, if you have the time, do think you could get it running on Travis CI?

**Comment by Thunderforge** [comment]
@Allofich I am using macOS, but I've never tried to set it up. I'm up for the challenge though.

However, I would think we would need to get #74 finished first. I got stuck with WildMidi support (I'm a C++ newbie and am used to Java dependencies). Would you be okay with a PR that built a Mac app, but had no sound as a known issue?

**Comment by afritz1** [comment]
From the looks of it, you already got it working on macOS (just without the music), so it seems to be almost supported. If you want, you can do a pull request for .travis.yml, and we can work from there. It's your choice (you're the residing macOS guy 😃).

I imagine that the .dylib problem is probably pretty easy to solve, but I have little to no experience with macOS, so I can only guess at this point. I haven't commented on that issue because I'm honestly not sure. Maybe it's a static/dynamic lib mix-up, or the program's being built with debug symbols and it's expecting libWildMidi.dylib to also have debug symbols, or the .dylib needs to be in the same directory as the executable, or something.

**Comment by Allofich** [comment]
> Would you be okay with a PR that built a Mac app, but had no sound as a known issue?

IMO, that would be still be useful.

One reason I suggested the macOS Travic CI build, is that I have noticed from following OpenMW that the macOS build will give warnings that the other builds won't, so it's another layer of code-checking (even if, worst-case, macOS builds aren't actually functional for some reason).

On that note, I don't know for sure, but again from following OpenMW, it seems like GCC never fails where Clang succeeds or warns on code that Clang doesn't. If building with Clang is just plain stricter than building with GCC, then maybe we code just drop the GCC build. But we'd probably first want to be sure there's no benefit to the GCC build, and as I said, I'm not sure of that.

**Comment by Thunderforge** [comment]
@Allofich Sorry of the delay in getting back. I'll take another look at the macOS PR and make sure that it still works with the latest code. Once that's done, I'll see if I can recruit a macOS dev who is more experienced in CMake to see if they can get it working there.

**Comment by Allofich** [comment]
No rush. As for getting Travis CI working, if you just add "os-x" by "compiler" and, as I wrote above, use a syntax like

`install:

if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install foo; else brew install bar; fi`

then we're already on our way, but the problem is I don't know what "bar" (the macOS dependencies) should be. Of course, additional problems may or may not come up after getting past this step.

**Comment by Thunderforge** [comment]
I made some good progress on getting this to work on my personal branch. However, [the status page](https://www.traviscistatus.com) notes that there are some huge delays with Mac builds (I'm still waiting for a build after 30 minutes).

This makes me wonder: do we need a Mac build with both Clang and GCC? Would it be better to just have a build for one of the two?

**Comment by afritz1** [comment]
Good work! I don't know enough about the differences between Linux and macOS compilers to answer that question, and I don't know if LLVM has anything to do with it, either. I imagine that each compiler is implemented differently enough that there would be enough reason to have both builds on macOS.

I've had a little bit of trouble with Travis CI builds not starting in the past, but it seems to be intermittent enough that it's not a big problem.

**Comment by afritz1** [comment]
See #102.

**Comment by Allofich** [comment]
Thanks Thunderforge!

A couple very minor nitpicks (just aesthetic things):

1. There's a warning in the macOS builds:

> clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]

I think it's coming from this part in CMakeLists.txt

> # To use std::thread and friends, we must pass -lpthread and -pthread to the compiler and Linker for >GCC
>    IF (NOT WIN32)
>        SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread")
>        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
>        SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -lpthread -pthread")
>    ENDIF (NOT WIN32)

2. The newly added files have the "No newline at end of file" warning. I think that's only a warning because it can interfere with some Unix file search operations or something (I researched it before but forget the details). Honestly it would mostly just be to get rid of the red warning symbol in GitHub :)

If you don't feel like it, I could send in a PR for it. And nice work!

**Comment by Allofich** [comment]
I'm preparing a PR. There's a massive backlog on the macOS Travis-CI builds that is slowly being chipped away at (apparently there was some issue that has been resolved now and a huge backlog built up). Once I know that the changes I made build on Travis-CI, I'll submit the PR.

**Comment by Thunderforge** [comment]
@Allofich Thanks for taking care of that. I'm guessing you're in a European time zone? I'm US Central, so I was sleeping when you sent those out. At any rate, I'm glad we got those warnings addressed.
