### ISSUE TITLE
Crystal Palace crashes

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#97]
The Crystal Palace (42488253.MIF) is crashing since commit https://github.com/afritz1/OpenTESArena/commit/ff454670edba2e6d6cb4af1bbac2579dda10b0c2.

Also, despite my bringing up the drums not-repeating issue earlier, I'd like to suggest that for now the repeating be commented out/disabled. It can very annoying when zooming around the levels to test them, which is what most people running the program now would probably be doing, and anyone whose following development and trying out builds could be sick to death of the sound by the time the game is actually playable.

**Comment by afritz1** [comment]
In the debugger it shows that it's having trouble parsing a line in `CRYSTAL3.INF` (specifically, `*ITEM 55` in the FLATS section with `Mage', 0`, a line that's probably unused). Looking into a fix now.

And with the repeating drums, yeah, I could disable that now or add an option for it. Just remember that it's less annoying now than if multiple instances were allowed to play at the same time 😄.

**Comment by Allofich** [comment]
> Just remember that it's less annoying now than if multiple instances were allowed to play at the same time 

No doubt :)

**Comment by afritz1** [comment]
See commits eeff3ca7bf485db8c838be4ccbffe7a280b8047a and f06fdba5da5558e369de903a7678a77e9d1a8fc4.
