### ISSUE TITLE
Sounds are not interrupted when opening the options or returning to the title menu

### ISSUE THREAD

**Issue by Allofich** [afritz1/OpenTESArena#98]
Mostly noticeable if you have the drums playing, since they're a long sound.

**Comment by Allofich** [comment]
I just tested and the original game has the same behavior. So, I guess it's a matter of taste/design goals. On first impression it seemed wrong, but The sound lingering on when you change screens can maybe be atmospheric in its own way. Anyway since it's not clearly a problem (I'm only aiming to report bugs and behavior that differs from the original) I'm fine with closing this.

**Comment by afritz1** [comment]
I was considering adding code to stop all sounds when going to the main menu, but if the original game lets sounds continue, then we should do it that way. It would add a feeling of cleanliness/closure by cutting off active sounds, but like you said, it can be atmospheric. Let's leave it as-is.
